apiVersion: v1
kind: Namespace
metadata:
  name: reactv2-1
  namespace: reactv2-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactv2-1
  namespace: reactv2-1
  labels:
    app: reactv2-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactv2-1
  template:
    metadata:
      labels:
        app: reactv2-1
    spec:
      serviceAccountName: demo-ldns
      containers:
        - name: reactv2-1
          image: codydearkland/ld-demo-reactv2:latest
          imagePullPolicy: Always
          env:
            - name: AWS_DEFAULT_REGION
              value: "us-east-2"
            - name: ENABLE_IRP
              value: "true"
          ports:
            - name: web
              containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: reactv2-1
  name: reactv2-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: reactv2-1
  type: LoadBalancer
